### ISSUE TITLE
Application landing page

### ISSUE THREAD

**Issue by monacofj** [flossschool/pollex#4]
Would someone write a first sketch of the application home page?

**Comment by Vakihito** [comment]
so i was working in a project, and i've made a template for the login, so if you guys want,
 i think we can use something like this, but maybe we will have to change the background image, since i don't know if it's legal to just use it 
but here's a picture of the template:
![Screenshot from 2019-11-18 19-52-52](https://user-images.githubusercontent.com/40372914/69101218-cc97ba80-0a3d-11ea-9f71-e0e48ca89de9.png)

**Comment by Vakihito** [comment]
so i was discussing with my group and we come up with this new idea, what do you guys think :
![Screenshot from 2019-11-19 12-33-37](https://user-images.githubusercontent.com/40372914/69160743-d61a3480-0ac8-11ea-822b-43852be8b867.png)

**Comment by henritarzia** [comment]
We made these templates for the login, sign in and main page. If there are any suggestions to improve the templates, feel free to modify the files. The CSS framework used is Bootstrap.
![index](https://user-images.githubusercontent.com/44980986/69482908-db94b900-0dff-11ea-8b7c-0b78d89ff33f.png)
![mainpage](https://user-images.githubusercontent.com/44980986/69482909-db94b900-0dff-11ea-860b-db80c87da392.png)
![signin](https://user-images.githubusercontent.com/44980986/69482910-db94b900-0dff-11ea-9a1d-4b7695ece89f.png)

**Comment by monacofj** [comment]
Should we consider this issue done and close it already?

**Comment by LuisF3** [comment]
Yes, closing...
